version: '3'
services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./data:/var
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - SYS_ADMIN
    command: /sbin/init
    ports:
      - '6030:8080'
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8
    restart: always